# Generated by Django 2.1.1 on 2018-10-14 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CBCS_Tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
